#!/usr/bin/env bash
#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
#####################################################
## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
export PATH="${PATH}:$HOME/.config/rofi/bin"
export SUDO_ASKPASS=askpass
export EDITOR=nvim
export BROWSER=firefox
export PAGER=bat
export RANGER_DEVICONS_SEPARATOR=" "
export _JAVA_AWT_WM_NONREPARENTING=1
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9

##########################################################################
#	functions
##########################################################################
xrdb -merge $HOME/.Xresources
xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

##########################################################################
#	autostart
##########################################################################

# xrandr setup
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCR
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
killall -9 sxhkd Dunst picom polkit-gnome eww polkit-gnome-authentication-agent-1
start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
start sxhkd
start picom
start dunst
xsetroot -cursor_name left_ptr &
$HOME/.fehbg &
set-monitors &
#killall scratchpad; alacritty --class scratchpad -e bash &
pgrep bspswallow || nohup bspswallow &
launchbar.sh &

##########################################################################
#	config
##########################################################################
#bspc monitor HDMI-A-0 -s DisplayPort-0
#bspc wm -O DisplayPort-0 HDMI-A-0
config border_width         2
config window_gap          12

config split_ratio          0.60
config borderless_monocle   true
config gapless_monocle      false
config focus_follows_pointer true
config pointer_follows_monitor true
config pointer_follows_focus false
config focus_by_distance true
config ignore_ewmh_focus true
config click_to_focus false 
config honor_size_hints true
config remove_disabled_monitors true
config remove_unplugged_monitors true
config pointer_modifier mod4
config pointer_action1 move
config pointer_action2 none
config pointer_action3 resize_corner


config normal_border_color "#c0caf5"
config focused_border_color "#7aa2f7"
config active_border_color "#7aa2f7"
config presel_border_color $BACKGROUND
config urgent_border_color $RED

# config focused_border_color "#70c0ba"
# config normal_border_color "#949494"
# config presel_border_color "#54ced6"
# config presel_feedback_color "#79dcaa"
# config urgent_border_color "#ffe59e"
# config focused_private_border_color "#f87070"


##########################################################################
# rules	
##########################################################################

rule -r *:*
rule Discord desktop='^5' state=fullscreen follow=off focus=off
rule ImageMagick state=floating focus=on center=true
rule feh state=floating follow=on center=true
rule kitty state=floating follow=on focus=on center=true rectangle 600x400+50+50
rule Arandr state=floating center=true rectangle 400x400+50+50
rule Pavucontrol state=floating center=true rectangle 400x400+50+50
rule Lxappearance state=floating center=true rectangle 400x400+50+50 
rule scratchpad sticky=on state=floating center=true hidden=on rectangle 650x400+50+50
rule "scratchpad" sticky=on state=floating center=true hidden=on rectangle 600x400+50+50
rule nm-connection-editor state=floating center=true rectangle 400x400+50+50
rule "Firefox:Save File" state=floating center=true rectangle 350x350+50+50
rule "Save File" state=floating center=true rectangle 400x400+50+50
rule jgmenu manage=off floating=true state=floating

